[package]
name = "ultra-sparse-bloom"
version = "0.1.0"
edition = "2024"

[dependencies]
twox-hash = "1.6"
rand = "0.8"
hashbrown = "0.14" # Faster than standard HashMap
criterion = "0.5"

[[bench]]
name = "benchmark"
harness = false
