[package]
name = "tropical-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
rand_distr = "0.4"
rayon = "1.7"
hnsw_rs = "0.1"
bit-vec = "0.6"
prettytable-rs = "0.10"
instant = "0.1"
